package:
  name: knotergy
  version: "0.2.4"

source:
  - path: ..

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make
    - pkg-config
    - git

  host:
    - viennarna =2.7.2
    - libstdcxx-ng # [linux]
    - libcxx       # [osx]

  run:
    - viennarna =2.7.2
    - libstdcxx-ng # [linux]
    - libcxx       # [osx]

test:
  commands:
    - Knotergy --help
    - Knotergy -s "AAAPUUU" -r "(.....)" -m

about:
  home: https://github.com/TheCOBRALab/Knotergy
  summary: "Knotergy is an algorithm for evaluating pseudoknotted secondary structures of RNA."
  description: |
    Knotergy evaluates RNA secondary structure.
  dev_url: https://github.com/TheCOBRALab/Knotergy

extra:
  recipe-maintainers:
    - PointlessUser