name: CMake on multiple platforms

on:
  workflow_dispatch:
  push:         { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13] # ubuntu-24.04-arm,
        build_type: [Release]
        include:
          - { os: ubuntu-latest   , c_compiler: gcc  , cpp_compiler: g++      }
          #- { os: ubuntu-24.04-arm, c_compiler: gcc  , cpp_compiler: g++      }
          - { os: macos-latest    , c_compiler: clang, cpp_compiler: clang++  }
          - { os: macos-13        , c_compiler: clang, cpp_compiler: clang++  }
    steps:
    - uses: actions/checkout@v4
      with: { submodules: true }
    
# -------------------- Build --------------------
    - name: Set reusable strings
      id: strings
      run: echo "build-output-dir=${{ github.workspace }}/build" >>"$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel

# -------------------- Test --------------------
    - name: Test Knotergy
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --output-on-failure
